version: '3'

services:
  rabbitmq:
    container_name: check-it-out-rabbitmq
    build: etc/infrastructure/rabbitmq
    restart: unless-stopped
    ports:
      - 8672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    container_name: check-it-out-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fpm

  fpm:
    container_name: check-it-out-fpm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2222:22"
      - "9090:9000"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - rabbitmq
